language: crystal

sudo: required
before_install: |
  curl -sL https://github.com/ysbaddaden/shards/releases/latest | \
  egrep -o '/ysbaddaden/shards/releases/download/v[0-9\.]*/shards.*linux_amd64.tar.gz' | \
  wget --base=http://github.com/ -i - -O - | \
  sudo tar xz -C /usr/local/bin
